import { CalendarEvent } from '../models/calendar-event.model';
import { DeepPartial } from '../models/deep-partial.model';
import { Season } from '../models/season.model';
import { Tag } from '../models/tag.model';

export const BIRTHDAY_EVENTS: DeepPartial<CalendarEvent>[] = [
  {
    title: "Abigail's Birthday",
    description: '',
    tag: Tag.Abigail,
    gameDate: { isRecurring: true, day: 13, season: Season.FALL },
  },
  {
    title: "Alex's Birthday",
    description: '',
    tag: Tag.Alex,
    gameDate: { isRecurring: true, day: 13, season: Season.SUMMER },
  },
  {
    title: "Caroline's Birthday",
    description: '',
    tag: Tag.Caroline,
    gameDate: { isRecurring: true, day: 7, season: Season.WINTER },
  },
  {
    title: "Clint's Birthday",
    description: '',
    tag: Tag.Clint,
    gameDate: { isRecurring: true, day: 26, season: Season.WINTER },
  },
  {
    title: "Demetrius's Birthday",
    description: '',
    tag: Tag.Demetrius,
    gameDate: { isRecurring: true, day: 19, season: Season.SUMMER },
  },
  {
    title: "Dwarf's Birthday",
    description: '',
    tag: Tag.Dwarf,
    gameDate: { isRecurring: true, day: 22, season: Season.SUMMER },
  },
  {
    title: "Elliott's Birthday",
    description: '',
    tag: Tag.Elliott,
    gameDate: { isRecurring: true, day: 5, season: Season.FALL },
  },
  {
    title: "Emily's Birthday",
    description: '',
    tag: Tag.Emily,
    gameDate: { isRecurring: true, day: 27, season: Season.SPRING },
  },
  {
    title: "Evelyn's Birthday",
    description: '',
    tag: Tag.Evelyn,
    gameDate: { isRecurring: true, day: 20, season: Season.WINTER },
  },
  {
    title: "George's Birthday",
    description: '',
    tag: Tag.George,
    gameDate: { isRecurring: true, day: 24, season: Season.FALL },
  },
  {
    title: "Gus's Birthday",
    description: '',
    tag: Tag.Gus,
    gameDate: { isRecurring: true, day: 8, season: Season.SUMMER },
  },
  {
    title: "Haley's Birthday",
    description: '',
    tag: Tag.Haley,
    gameDate: { isRecurring: true, day: 14, season: Season.SPRING },
  },
  {
    title: "Harvey's Birthday",
    description: '',
    tag: Tag.Harvey,
    gameDate: { isRecurring: true, day: 14, season: Season.WINTER },
  },
  {
    title: "Jas's Birthday",
    description: '',
    tag: Tag.Jas,
    gameDate: { isRecurring: true, day: 4, season: Season.SUMMER },
  },
  {
    title: "Jodi's Birthday",
    description: '',
    tag: Tag.Jodi,
    gameDate: { isRecurring: true, day: 11, season: Season.FALL },
  },
  {
    title: "Kent's Birthday",
    description: '',
    tag: Tag.Kent,
    gameDate: { isRecurring: true, day: 4, season: Season.SPRING },
  },
  {
    title: "Krobus's Birthday",
    description: '',
    tag: Tag.Krobus,
    gameDate: { isRecurring: true, day: 1, season: Season.WINTER },
  },
  {
    title: "Leah's Birthday",
    description: '',
    tag: Tag.Leah,
    gameDate: { isRecurring: true, day: 23, season: Season.WINTER },
  },
  {
    title: "Leo's Birthday",
    description: '',
    tag: Tag.Leo,
    gameDate: { isRecurring: true, day: 26, season: Season.SUMMER },
  },
  {
    title: "Lewis's Birthday",
    description: '',
    tag: Tag.Lewis,
    gameDate: { isRecurring: true, day: 7, season: Season.SPRING },
  },
  {
    title: "Linus's Birthday",
    description: '',
    tag: Tag.Linus,
    gameDate: { isRecurring: true, day: 3, season: Season.WINTER },
  },
  {
    title: "Marlon's Birthday",
    description: '',
    tag: Tag.Marlon,
    gameDate: { isRecurring: true, day: 19, season: Season.WINTER },
  },
  {
    title: "Marnie's Birthday",
    description: '',
    tag: Tag.Marnie,
    gameDate: { isRecurring: true, day: 18, season: Season.FALL },
  },
  {
    title: "Maru's Birthday",
    description: '',
    tag: Tag.Maru,
    gameDate: { isRecurring: true, day: 10, season: Season.SUMMER },
  },
  {
    title: "Morris's Birthday",
    description: '',
    tag: Tag.Morris,
    gameDate: { isRecurring: true, day: 2, season: Season.SPRING },
  },
  {
    title: "Pam's Birthday",
    description: '',
    tag: Tag.Pam,
    gameDate: { isRecurring: true, day: 18, season: Season.SPRING },
  },
  {
    title: "Penny's Birthday",
    description: '',
    tag: Tag.Penny,
    gameDate: { isRecurring: true, day: 2, season: Season.FALL },
  },
  {
    title: "Pierre's Birthday",
    description: '',
    tag: Tag.Pierre,
    gameDate: { isRecurring: true, day: 26, season: Season.SPRING },
  },
  {
    title: "Robin's Birthday",
    description: '',
    tag: Tag.Robin,
    gameDate: { isRecurring: true, day: 21, season: Season.FALL },
  },
  {
    title: "Sam's Birthday",
    description: '',
    tag: Tag.Sam,
    gameDate: { isRecurring: true, day: 17, season: Season.SUMMER },
  },
  {
    title: "Sandy's Birthday",
    description: '',
    tag: Tag.Sandy,
    gameDate: { isRecurring: true, day: 15, season: Season.FALL },
  },
  {
    title: "Sebastian's Birthday",
    description: '',
    tag: Tag.Sebastian,
    gameDate: { isRecurring: true, day: 10, season: Season.WINTER },
  },
  {
    title: "Shane's Birthday",
    description: '',
    tag: Tag.Shane,
    gameDate: { isRecurring: true, day: 20, season: Season.SPRING },
  },
  {
    title: "Vincent's Birthday",
    description: '',
    tag: Tag.Vincent,
    gameDate: { isRecurring: true, day: 10, season: Season.SPRING },
  },
  {
    title: "Willy's Birthday",
    description: '',
    tag: Tag.Willy,
    gameDate: { isRecurring: true, day: 24, season: Season.SUMMER },
  },
  {
    title: "Wizard's Birthday",
    description: '',
    tag: Tag.Wizard,
    gameDate: { isRecurring: true, day: 17, season: Season.WINTER },
  },
];
