import { UnsavedGameEvent } from '../models/game-event.model';
import { Season } from '../models/season.model';
import { Tag } from '../models/tag.model';
import { Type } from '../models/type.model';

const SPRING_CROPS_DEADLINE: UnsavedGameEvent[] = [
  {
    title: 'LAST DAY: Blue Jazz',
    description: `Sells for 50g.\n7 days to harvest.`,
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 21, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Cauliflower',
    description: 'Sells for 175g.\n12 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 16, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Coffee Bean',
    description: 'Sells for 15g.\n10 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 18, season: Season.SPRING },
    type: Type.SystemCrops,
  },

  {
    title: 'LAST DAY: Garlic',
    description: 'Sells for 60g.\n4 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 24, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Green Beans',
    description: 'Sells for 40g.\n10 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 18, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Kale',
    description: 'Sells for 110g.\n6 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 22, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Parsnip',
    description: 'Sells for 35.\n4 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 24, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Potato',
    description: 'Sells for 80g.\n6 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 22, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Rhubarb',
    description: 'Sells for 220g.\n13 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 15, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Strawberry',
    description: 'Sells for 120g.\n8 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 20, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Tulip',
    description: 'Sells for 30g.\n6 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 22, season: Season.SPRING },
    type: Type.SystemCrops,
  },
];
const SUMMER_CROPS_DEADLINE: UnsavedGameEvent[] = [
  {
    title: 'LAST DAY: Blueberry',
    description: 'Sells for 50g.\n13 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 15, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Coffee Bean',
    description: 'Sells for 15g.\n10 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 18, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Corn',
    description: 'Sells for 50g.\n14 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 14, season: Season.SUMMER },
    type: Type.SystemCrops,
  },

  {
    title: 'LAST DAY: Hops',
    description: 'Sells for 25g.\n11 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 17, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Hot Pepper',
    description: 'Sells for 40g.\n5 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 23, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Melon',
    description: 'Sells for 250g.\n12 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 16, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Poppy',
    description: 'Sells for 140g.\n7 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 21, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Radish',
    description: 'Sells for 90g.\n6 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 22, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Red Cabbage',
    description: 'Sells for 260g.\n9 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 19, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Starfruit',
    description: 'Sells for 750g.\n13 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 15, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Summer Spangle',
    description: 'Sells for 90g.\n8 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 20, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Sunflower',
    description: 'Sells for 80g.\n8 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 20, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Tomato',
    description: 'Sells for 60g.\n11 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 17, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Wheat',
    description: 'Sells for 25g.\n4 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 24, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
];
const FALL_CROPS_DEADLINE: UnsavedGameEvent[] = [
  {
    title: 'LAST DAY: Wheat',
    description: 'Sells for 25g.\n4 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 24, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Sunflower',
    description: 'Sells for 80g.\n8 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 20, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Corn',
    description: 'Sells for 50g.\n14 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 14, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Amaranth',
    description: 'Sells for 150g.\n7 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 21, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Artichoke',
    description: 'Sells for 160g.\n8 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 20, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Beet',
    description: 'Sells for 100g.\n6 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 22, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Bok Choy',
    description: 'Sells for 80g.\n4 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 24, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Cranberries',
    description: 'Sells for 75g.\n7 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 21, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Eggplant',
    description: 'Sells for 60g.\n5 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 23, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Fairy Rose',
    description: 'Sells for 290g.\n12 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 16, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Grape',
    description: 'Sells for 80g.\n10 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 18, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Pumpkin',
    description: 'Sells for 320g.\n13 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 15, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Yam',
    description: 'Sells for 160g.\n10 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 18, season: Season.FALL },
    type: Type.SystemCrops,
  },
];
const SPECIAL_CROPS_DEADLINE: UnsavedGameEvent[] = [
  {
    title: 'LAST DAY: Sweet Gem Berry',
    description: 'Sells for 3000g.\n24 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 4, season: Season.FALL },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Ancient Fruit',
    description: 'Sells for 550g.\n28 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 28, season: Season.WINTER },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Ancient Fruit',
    description: 'Sells for 550g.\n28 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 28, season: Season.SPRING },
    type: Type.SystemCrops,
  },
  {
    title: 'LAST DAY: Ancient Fruit',
    description: 'Sells for 550g.\n28 days to harvest.',
    tag: Tag.Crop,
    gameDate: { isRecurring: true, day: 28, season: Season.SUMMER },
    type: Type.SystemCrops,
  },
];

export const CROPS_DEADLINES: UnsavedGameEvent[] = [
  ...SPRING_CROPS_DEADLINE,
  ...SUMMER_CROPS_DEADLINE,
  ...FALL_CROPS_DEADLINE,
  ...SPECIAL_CROPS_DEADLINE,
];
