import { TagCategory } from '../models/tag-category.model';
import { TagMetadata } from '../models/tag-metadata.model';
import { Tag } from '../models/tag.model';

export const TAG_METADATA: Map<Tag, TagMetadata> = new Map([
  [Tag.Abigail, { category: TagCategory.CHARACTER, url: 'abigail-icon.png' }],
  [Tag.Alex, { category: TagCategory.CHARACTER, url: 'alex-icon.png' }],
  [Tag.Amaranth, { category: TagCategory.CROP, url: 'amaranth-icon.png' }],
  [
    Tag.AncientFruit,
    { category: TagCategory.CROP, url: 'ancient-fruit-icon.png' },
  ],
  [Tag.Artichoke, { category: TagCategory.CROP, url: 'artichoke-icon.png' }],
  [Tag.Artisan, { category: TagCategory.ACTIVITY, url: 'artisan-icon.png' }],
  [Tag.Beet, { category: TagCategory.CROP, url: 'beet-icon.png' }],
  [Tag.Blueberry, { category: TagCategory.CROP, url: 'blueberry-icon.png' }],
  [Tag.BlueJazz, { category: TagCategory.CROP, url: 'blue-jazz-icon.png' }],
  [Tag.BokChoy, { category: TagCategory.CROP, url: 'bok-choy-icon.png' }],
  [Tag.Broccoli, { category: TagCategory.CROP, url: 'broccoli-icon.png' }],
  [Tag.Building, { category: TagCategory.ACTIVITY, url: 'barn-icon.png' }],
  [
    Tag.CactusFruit,
    { category: TagCategory.CROP, url: 'cactus-fruit-icon.png' },
  ],
  [Tag.Caroline, { category: TagCategory.CHARACTER, url: 'caroline-icon.png' }],
  [Tag.Carrot, { category: TagCategory.CROP, url: 'carrot-icon.png' }],
  [
    Tag.Cauliflower,
    { category: TagCategory.CROP, url: 'cauliflower-icon.png' },
  ],
  [Tag.Clint, { category: TagCategory.CHARACTER, url: 'clint-icon.png' }],
  [Tag.CoffeeBean, { category: TagCategory.CROP, url: 'coffee-bean-icon.png' }],
  [Tag.Corn, { category: TagCategory.CROP, url: 'corn-icon.png' }],
  [
    Tag.Cranberries,
    { category: TagCategory.CROP, url: 'cranberries-icon.png' },
  ],
  [
    Tag.Demetrius,
    { category: TagCategory.CHARACTER, url: 'demetrius-icon.png' },
  ],
  [Tag.Dwarf, { category: TagCategory.CHARACTER, url: 'dwarf-icon.png' }],
  [Tag.Eggplant, { category: TagCategory.CROP, url: 'eggplant-icon.png' }],
  [Tag.Elliott, { category: TagCategory.CHARACTER, url: 'elliott-icon.png' }],
  [Tag.Emily, { category: TagCategory.CHARACTER, url: 'emily-icon.png' }],
  [Tag.Evelyn, { category: TagCategory.CHARACTER, url: 'evelyn-icon.png' }],
  [Tag.FairyRose, { category: TagCategory.CROP, url: 'fairy-rose-icon.png' }],
  [Tag.Farming, { category: TagCategory.ACTIVITY, url: 'farming-icon.png' }],
  [
    Tag.Festival,
    { category: TagCategory.ACTIVITY, url: 'calendar-flag-icon.png' },
  ],
  [Tag.Fishing, { category: TagCategory.ACTIVITY, url: 'fishing-icon.png' }],
  [Tag.Foraging, { category: TagCategory.ACTIVITY, url: 'daffodil-icon.png' }],
  [Tag.Garlic, { category: TagCategory.CROP, url: 'garlic-icon.png' }],
  [Tag.George, { category: TagCategory.CHARACTER, url: 'george-icon.png' }],
  [Tag.Gift, { category: TagCategory.ACTIVITY, url: 'gift-icon.png' }],
  [Tag.Grape, { category: TagCategory.CROP, url: 'grape-icon.png' }],
  [Tag.GreenBean, { category: TagCategory.CROP, url: 'green-bean-icon.png' }],
  [Tag.Gus, { category: TagCategory.CHARACTER, url: 'gus-icon.png' }],
  [Tag.Haley, { category: TagCategory.CHARACTER, url: 'haley-icon.png' }],
  [Tag.Harvey, { category: TagCategory.CHARACTER, url: 'harvey-icon.png' }],
  [Tag.Hops, { category: TagCategory.CROP, url: 'hops-icon.png' }],
  [Tag.HotPepper, { category: TagCategory.CROP, url: 'hot-pepper-icon.png' }],
  [Tag.Jas, { category: TagCategory.CHARACTER, url: 'jas-icon.png' }],
  [Tag.Jodi, { category: TagCategory.CHARACTER, url: 'jodi-icon.png' }],
  [Tag.Kale, { category: TagCategory.CROP, url: 'kale-icon.png' }],
  [Tag.Kent, { category: TagCategory.CHARACTER, url: 'kent-icon.png' }],
  [Tag.Krobus, { category: TagCategory.CHARACTER, url: 'krobus-icon.png' }],
  [Tag.Leah, { category: TagCategory.CHARACTER, url: 'leah-icon.png' }],
  [Tag.Leo, { category: TagCategory.CHARACTER, url: 'leo-icon.png' }],
  [Tag.Lewis, { category: TagCategory.CHARACTER, url: 'lewis-icon.png' }],
  [Tag.Linus, { category: TagCategory.CHARACTER, url: 'linus-icon.png' }],
  [Tag.Marlon, { category: TagCategory.CHARACTER, url: 'marlon-icon.png' }],
  [Tag.Marnie, { category: TagCategory.CHARACTER, url: 'marnie-icon.png' }],
  [Tag.Maru, { category: TagCategory.CHARACTER, url: 'maru-icon.png' }],
  [Tag.Melon, { category: TagCategory.CROP, url: 'melon-icon.png' }],
  [Tag.Mining, { category: TagCategory.ACTIVITY, url: 'mining-icon.png' }],
  [Tag.Morris, { category: TagCategory.CHARACTER, url: 'morris-icon.png' }],
  [Tag.Pam, { category: TagCategory.CHARACTER, url: 'pam-icon.png' }],
  [Tag.Parsnip, { category: TagCategory.CROP, url: 'parsnip-icon.png' }],
  [Tag.Penny, { category: TagCategory.CHARACTER, url: 'penny-icon.png' }],
  [Tag.Pierre, { category: TagCategory.CHARACTER, url: 'pierre-icon.png' }],
  [Tag.Pineapple, { category: TagCategory.CROP, url: 'pineapple-icon.png' }],
  [Tag.Poppy, { category: TagCategory.CROP, url: 'poppy-icon.png' }],
  [Tag.Potato, { category: TagCategory.CROP, url: 'potato-icon.png' }],
  [
    Tag.Powdermelon,
    { category: TagCategory.CROP, url: 'powdermelon-icon.png' },
  ],
  [Tag.Pumpkin, { category: TagCategory.CROP, url: 'pumpkin-icon.png' }],
  [Tag.Radish, { category: TagCategory.CROP, url: 'radish-icon.png' }],
  [Tag.RedCabbage, { category: TagCategory.CROP, url: 'red-cabbage-icon.png' }],
  [Tag.Rhubarb, { category: TagCategory.CROP, url: 'rhubarb-icon.png' }],
  [Tag.Rice, { category: TagCategory.CROP, url: 'rice-icon.png' }],
  [Tag.Robin, { category: TagCategory.CHARACTER, url: 'robin-icon.png' }],
  [Tag.Sam, { category: TagCategory.CHARACTER, url: 'sam-icon.png' }],
  [Tag.Sandy, { category: TagCategory.CHARACTER, url: 'sandy-icon.png' }],
  [
    Tag.Sebastian,
    { category: TagCategory.CHARACTER, url: 'sebastian-icon.png' },
  ],
  [Tag.Shane, { category: TagCategory.CHARACTER, url: 'shane-icon.png' }],
  [Tag.Starfruit, { category: TagCategory.CROP, url: 'starfruit-icon.png' }],
  [Tag.Strawberry, { category: TagCategory.CROP, url: 'strawberry-icon.png' }],
  [
    Tag.SummerSpangle,
    { category: TagCategory.CROP, url: 'summer-spangle-icon.png' },
  ],
  [
    Tag.SummerSquash,
    { category: TagCategory.CROP, url: 'summer-squash-icon.png' },
  ],
  [Tag.Sunflower, { category: TagCategory.CROP, url: 'sunflower-icon.png' }],
  [
    Tag.SweetGemBerry,
    { category: TagCategory.CROP, url: 'sweet-gem-berry-icon.png' },
  ],
  [Tag.TaroRoot, { category: TagCategory.CROP, url: 'taro-root-icon.png' }],
  [Tag.TeaLeaves, { category: TagCategory.CROP, url: 'tea-leaves-icon.png' }],
  [Tag.Tomato, { category: TagCategory.CROP, url: 'tomato-icon.png' }],
  [Tag.Tulip, { category: TagCategory.CROP, url: 'tulip-icon.png' }],
  [Tag.Vincent, { category: TagCategory.CHARACTER, url: 'vincent-icon.png' }],
  [Tag.Wheat, { category: TagCategory.CROP, url: 'wheat-icon.png' }],
  [Tag.Willy, { category: TagCategory.CHARACTER, url: 'willy-icon.png' }],
  [Tag.Wizard, { category: TagCategory.CHARACTER, url: 'wizard-icon.png' }],
  [Tag.Yam, { category: TagCategory.CROP, url: 'yam-icon.png' }],
]);
