// Interface automatically generated by schemas-to-ts

import { GameDate, GameDate_NoRelations, GameDate_Plain } from './game-date';

export enum Priority {
  Game = 'game',
  High = 'high',
  Medium = 'medium',
  Low = 'low',
}

export interface Event {
  title: string;
  priority: Priority;
  description: string;
  player?: string;
  dueDate?: GameDate;
}
export interface Event_Plain {
  title: string;
  priority: Priority;
  description: string;
  player?: string;
  dueDate?: GameDate_Plain;
}

export interface Event_NoRelations {
  title: string;
  priority: Priority;
  description: string;
  player?: string;
  dueDate?: GameDate_NoRelations;
}
