// Interface automatically generated by schemas-to-ts

import { GameDateComponent } from './GameDateComponent';
import { GameDateComponent_Plain } from './GameDateComponent';
import { GameDateComponent_NoRelations } from './GameDateComponent';

export enum Tag {
  Crop = 'crop',
  Birthday = 'birthday',
  Building = 'building',
  Festival = 'festival',
  Abigail = 'abigail',
  Alex = 'alex',
  Birdie = 'birdie',
  Bouncer = 'bouncer',
  Caroline = 'caroline',
  Clint = 'clint',
  Demetrius = 'demetrius',
  Dwarf = 'dwarf',
  Elliott = 'elliott',
  Emily = 'emily',
  Evelyn = 'evelyn',
  George = 'george',
  Gil = 'gil',
  Governor = 'governor',
  Grandpa = 'grandpa',
  Gunther = 'gunther',
  Gus = 'gus',
  Haley = 'haley',
  Harvey = 'harvey',
  Jas = 'jas',
  Jodi = 'jodi',
  Kent = 'kent',
  Krobus = 'krobus',
  Leah = 'leah',
  Leo = 'leo',
  Lewis = 'lewis',
  Linus = 'linus',
  Marlon = 'marlon',
  Marnie = 'marnie',
  Maru = 'maru',
  Morris = 'morris',
  MrQi = 'mr. qi',
  Pam = 'pam',
  Penny = 'penny',
  Pierre = 'pierre',
  Robin = 'robin',
  Sam = 'sam',
  Sandy = 'sandy',
  Sebastian = 'sebastian',
  Shane = 'shane',
  Vincent = 'vincent',
  Willy = 'willy',
  Wizard = 'wizard',}

export interface GameEventComponent {
  title: string;
  description: string;
  gameDate: GameDateComponent;
  tag: Tag;
}
export interface GameEventComponent_Plain {
  title: string;
  description: string;
  gameDate: GameDateComponent_Plain;
  tag: Tag;
}

export interface GameEventComponent_NoRelations {
  title: string;
  description: string;
  gameDate: GameDateComponent_NoRelations;
  tag: Tag;
}

