// Interface automatically generated by schemas-to-ts

import { GameDateComponent } from './GameDateComponent';
import { GameDateComponent_Plain } from './GameDateComponent';
import { GameDateComponent_NoRelations } from './GameDateComponent';

export enum Tag {
  HighPriority = 'highPriority',
  MediumPriority = 'mediumPriority',
  LowPriority = 'lowPriority',}

export interface GameEventComponent {
  title: string;
  description: string;
  dueDate?: GameDateComponent;
  gameDate: GameDateComponent;
  tag: Tag;
}
export interface GameEventComponent_Plain {
  title: string;
  description: string;
  dueDate?: GameDateComponent_Plain;
  gameDate: GameDateComponent_Plain;
  tag: Tag;
}

export interface GameEventComponent_NoRelations {
  title: string;
  description: string;
  dueDate?: GameDateComponent_NoRelations;
  gameDate: GameDateComponent_NoRelations;
  tag: Tag;
}

