// Interface automatically generated by schemas-to-ts
import {
  GameEventComponent,
  GameEventComponent_NoRelations,
  GameEventComponent_Plain,
} from './GameEventComponent';

export interface Calendar_Data {
  id: string;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    gameEvents: GameEventComponent[];
  };
}
export interface Calendar_Plain {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  gameEvents: GameEventComponent_Plain[];
}

export interface Calendar_NoRelations {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  gameEvents: GameEventComponent_NoRelations[];
}

export interface Calendar_AdminPanelLifeCycle {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  gameEvents: GameEventComponent_Plain[];
}
