// Interface automatically generated by schemas-to-ts
import { GameEvent_Data, GameEvent_Plain } from './game-event';
import { GameEventComponent_Plain } from './GameEventComponent';

export interface Calendar_Data {
  id: string;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    gameEvents: { data: GameEvent_Data[] };
  };
}
export interface Calendar_Plain {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  gameEvents: GameEvent_Plain[];
}

export interface Calendar_NoRelations {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  gameEvents: number[];
}

export interface Calendar_AdminPanelLifeCycle {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  gameEvents: GameEventComponent_Plain[];
}
