// Interface automatically generated by schemas-to-ts

import {
  GameDateComponent,
  GameDateComponent_NoRelations,
  GameDateComponent_Plain,
} from './GameDateComponent';

export enum Tag {
  HIGH_PRIORITY = 'highPriority',
  MEDIUM_PRIORITY = 'mediumPriority',
  LOW_PRIORITY = 'lowPriority',
}

export interface GameEventComponent {
  id: string;
  title: string;
  description: string;
  dueDate?: GameDateComponent;
  gameDate: GameDateComponent;
  tag: Tag;
}
export interface GameEventComponent_Plain {
  title: string;
  description: string;
  dueDate?: GameDateComponent_Plain;
  gameDate: GameDateComponent_Plain;
  tag: Tag;
}

export interface GameEventComponent_NoRelations {
  title: string;
  description: string;
  dueDate?: GameDateComponent_NoRelations;
  gameDate: GameDateComponent_NoRelations;
  tag: Tag;
}
