// Interface automatically generated by schemas-to-ts

export interface SystemConfigComponent {
  includeBirthdays: boolean;
  includeCrops: boolean;
  includeFestivals: boolean;
}
export interface SystemConfigComponent_Plain {
  includeBirthdays: boolean;
  includeCrops: boolean;
  includeFestivals: boolean;
}

export interface SystemConfigComponent_NoRelations {
  includeBirthdays: boolean;
  includeCrops: boolean;
  includeFestivals: boolean;
}

