// Interface automatically generated by schemas-to-ts

import { GameDateComponent } from '../../../../components/calendar/interfaces/GameDateComponent';
import { GameDateComponent_Plain } from '../../../../components/calendar/interfaces/GameDateComponent';
import { GameDateComponent_NoRelations } from '../../../../components/calendar/interfaces/GameDateComponent';

export enum Tag {
  Abigail = 'abigail',
  Alex = 'alex',
  Amaranth = 'amaranth',
  AncientFruit = 'ancientFruit',
  Artichoke = 'artichoke',
  Artisan = 'artisan',
  Beet = 'beet',
  Blueberry = 'blueberry',
  BlueJazz = 'blueJazz',
  BokChoy = 'bokChoy',
  Broccoli = 'broccoli',
  Building = 'building',
  CactusFruit = 'cactusFruit',
  Caroline = 'caroline',
  Carrot = 'carrot',
  Cauliflower = 'cauliflower',
  Clint = 'clint',
  CoffeeBean = 'coffeeBean',
  Corn = 'corn',
  Cranberries = 'cranberries',
  Demetrius = 'demetrius',
  Dwarf = 'dwarf',
  Eggplant = 'eggplant',
  Elliott = 'elliott',
  Emily = 'emily',
  Evelyn = 'evelyn',
  FairyRose = 'fairyRose',
  Farming = 'farming',
  Festival = 'festival',
  Fishing = 'fishing',
  Foraging = 'foraging',
  Garlic = 'garlic',
  George = 'george',
  Gift = 'gift',
  Grape = 'grape',
  GreenBean = 'greenBean',
  Gus = 'gus',
  Haley = 'haley',
  Harvey = 'harvey',
  Hops = 'hops',
  HotPepper = 'hotPepper',
  Jas = 'jas',
  Jodi = 'jodi',
  Kale = 'kale',
  Kent = 'kent',
  Krobus = 'krobus',
  Leah = 'leah',
  Leo = 'leo',
  Lewis = 'lewis',
  Linus = 'linus',
  Marlon = 'marlon',
  Marnie = 'marnie',
  Maru = 'maru',
  Melon = 'melon',
  Mining = 'mining',
  Morris = 'morris',
  Pam = 'pam',
  Parsnip = 'parsnip',
  Penny = 'penny',
  Pierre = 'pierre',
  Pineapple = 'pineapple',
  Poppy = 'poppy',
  Potato = 'potato',
  Powdermelon = 'powdermelon',
  Pumpkin = 'pumpkin',
  Radish = 'radish',
  RedCabbage = 'redCabbage',
  Rhubarb = 'rhubarb',
  Rice = 'rice',
  Robin = 'robin',
  Sam = 'sam',
  Sandy = 'sandy',
  Sebastian = 'sebastian',
  Shane = 'shane',
  Starfruit = 'starfruit',
  Strawberry = 'strawberry',
  SummerSpangle = 'summerSpangle',
  SummerSquash = 'summerSquash',
  Sunflower = 'sunflower',
  SweetGemBerry = 'sweetGemBerry',
  TaroRoot = 'taroRoot',
  TeaLeaves = 'teaLeaves',
  Tomato = 'tomato',
  Tulip = 'tulip',
  Vincent = 'vincent',
  Wheat = 'wheat',
  Willy = 'willy',
  Wizard = 'wizard',
  Yam = 'yam',}
export enum Type {
  SystemBirthdays = 'system_birthdays',
  SystemCrops = 'system_crops',
  SystemFestivals = 'system_festivals',
  User = 'user',}

export interface GameEvent {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: string;
    tag: Tag;
    gameDate: GameDateComponent;
    type: Type;
  };
}
export interface GameEvent_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  tag: Tag;
  gameDate: GameDateComponent_Plain;
  type: Type;
}

export interface GameEvent_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  tag: Tag;
  gameDate: GameDateComponent_NoRelations;
  type: Type;
}

export interface GameEvent_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  tag: Tag;
  gameDate: GameDateComponent_Plain;
  type: Type;
}
