// Interface automatically generated by schemas-to-ts

import { GameEvent } from '../../../game-event/content-types/game-event/game-event';
import { GameEvent_Plain } from '../../../game-event/content-types/game-event/game-event';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Calendar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    gameEvents: { data: GameEvent[] };
  };
}
export interface Calendar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  gameEvents: GameEvent_Plain[];
}

export interface Calendar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  gameEvents: number[];
}

export interface Calendar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  gameEvents: AdminPanelRelationPropertyModification<GameEvent_Plain>;
}
