// Interface automatically generated by schemas-to-ts

import { CalendarEvent } from '../../../calendar-event/content-types/calendar-event/calendar-event';
import { CalendarEvent_Plain } from '../../../calendar-event/content-types/calendar-event/calendar-event';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Calendar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    calendarEvents: { data: CalendarEvent[] };
    name: string;
  };
}
export interface Calendar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  calendarEvents: CalendarEvent_Plain[];
  name: string;
}

export interface Calendar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  calendarEvents: number[];
  name: string;
}

export interface Calendar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  calendarEvents: AdminPanelRelationPropertyModification<CalendarEvent_Plain>;
  name: string;
}
