// Interface automatically generated by schemas-to-ts

import { GameEventComponent } from '../../../../components/calendar/interfaces/GameEventComponent';
import { GameEventComponent_Plain } from '../../../../components/calendar/interfaces/GameEventComponent';
import { GameEventComponent_NoRelations } from '../../../../components/calendar/interfaces/GameEventComponent';

export interface Calendar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    gameEvents: GameEventComponent[];
  };
}
export interface Calendar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  gameEvents: GameEventComponent_Plain[];
}

export interface Calendar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  gameEvents: GameEventComponent_NoRelations[];
}

export interface Calendar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  gameEvents: GameEventComponent_Plain[];
}
